### ISSUE TITLE
Consuming a scoped service

### ISSUE THREAD

**Issue by vankampenp** [kdcllc/CronScheduler.AspNetCore#17]
In my app, I wanted to have a scheduled task that does some user admin things, such as sending reminders, cleaning up users. That the implementation uses the UserManager from Indentity Management.
When transferring this cleanup to the new scheduled service, I ran in to a run time error, as you cannot consume a scoped service in a singleton. That makes sense, I had overlooked the fact that the UserManager is a scoped service. 

Since the scheduler service itself is also a singleton, it is also not possible when I skipped the implementation of my own service, and just handle the task directly from the Job.

In the attached repo, I have created a simple service named ScopedService and registered it as a scoped service. When you run the app, you see the error.
The singleton ScopedIssueService is called from the Job and refers to the ScopedService, giving the error.

When changing the ScopedIssueService to Transient or Scoped, you will see the error is now on the ScheduledJob level as the IScheduledJob is a singleton.

On advise of @kdcllc I added a different service CreateScopeService, which creates a local scope:
```

            using (var scope = Services.CreateScope())
            {
                var scopedProcessingService = 
                    scope.ServiceProvider
                        .GetRequiredService<ScopedService>();

                return $"scoped: {scopedProcessingService.Ping()}";
            }

``` 
This works! It also seems to work with UserManager. However, it is not a silver bullet, I tried to obtain the httpcontext in the scoped service, and this (off course) does not work. It does not return an error, but the GetRequiredService never returns.

So my question is, should this be safe to use with the UserManager? I have no idea why this is a scoped service in the first place. 
If it is save, my suggestion would be to add this CreateScope solution to the documentation.

thx, Pieter
 
[CronSchedulerScopedIssue.zip](https://github.com/kdcllc/CronScheduler.AspNetCore/files/3513380/CronSchedulerScopedIssue.zip)

**Comment by kdcllc** [comment]
@vankampenp,
I have updated the sample application and the documentation accordingly. I also attached your sample code with some updates.

It is thread-safe to use `UserManager` within the `ScheduleJob` as you have mentioned. 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task

It is possible to use `IHttpContextAccessor` inside the objects but I would not recommend it.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.2#use-httpcontext-from-custom-components

I hope this helps, kdcllc
[CronSchedulerScopedIssue.zip](https://github.com/kdcllc/CronScheduler.AspNetCore/files/3518139/CronSchedulerScopedIssue.zip)

**Comment by vankampenp** [comment]
Great thx!
