### ISSUE TITLE
schedule executing twice per day instead of once

### ISSUE THREAD

**Issue by vankampenp** [kdcllc/CronScheduler.AspNetCore#22]
Hi, 
I have the following options set for my scheduler job:
 "CleanupJob": {
      "CronSchedule": "2 9 * * *",
      "RunImmediately": false,
      "Enabled": true
   }
It runs at 9:02 every day as expected, but it also runs at 11:02. The same is true for the other job I have, it also runs twice with 2 hours in between.
I am using v1.1.0 from Nuget, on netcoreapp2.2
Pieter

**Comment by kdcllc** [comment]
@vankampenp,

I looked over the code and updated it to change from `DateTime` to `DateTimeOffset` for the comparison of date time values. In addition, the next time is calculated based on the `TimeZoneInfo`.

I tested the updated code on my end and it looks good. Can you test the preview of it I made available?

[CronScheduler.AspNetCore 1.1.2-preview1](https://www.myget.org/feed/kdcllc/package/nuget/CronScheduler.AspNetCore)

```cmd
Install-Package CronScheduler.AspNetCore -Version 1.1.2-preview1 -Source https://www.myget.org/F/kdcllc/api/v3/index.json
````

**Comment by kdcllc** [comment]
@vankampenp, do you have an update on this?

**Comment by Externius** [comment]
@kdcllc I also had this problem. It’s fixed now with this preview repo (doesn’t run the job after 2 hours again).

**Comment by kdcllc** [comment]
@Externius  and @vankampenp I have merged the branch, so the new package is available now `dotnet add package CronScheduler.AspNetCore --version 1.1.1`

I also updated `.NET Core Workers Example`.

Thanks for the feedback.

**Comment by vankampenp** [comment]
Sorry for the late response, I had missed the earlier update. I tested it this morning and it works fine. Thanks.
