### ISSUE TITLE
Can't build when referencing CronScheduler.AspNetCore in 3.0 

### ISSUE THREAD

**Issue by hallidev** [kdcllc/CronScheduler.AspNetCore#25]
The following dependency fails to resolve using the last NetCoreApp 3.0:

Microsoft.AspNetCore.Hosting (>= 3.0.0-preview4-19123-01)

Full error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Microsoft.AspNetCore.Hosting with version (>= 3.0.0-preview4-19123-01)
  - Found 29 version(s) in nuget.org [ Nearest version: 2.2.7 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages

**Comment by vankampenp** [comment]
The dependencies are 
 "CronScheduler.AspNetCore/1.1.2": {
        "type": "package",
        "dependencies": {
          "Cronos": "0.7.0",
          "Microsoft.AspNetCore.Hosting": "3.0.0-preview4-19123-01",
          "Microsoft.Extensions.DependencyInjection": "3.0.0-preview8.19405.4",
          "Microsoft.Extensions.Hosting.Abstractions": "3.0.0-preview8.19405.4",
          "Microsoft.Extensions.Options.ConfigurationExtensions": "3.0.0-preview8.19405.4"
        },
        "compile": {
          "lib/netcoreapp3.0/CronScheduler.AspNetCore.dll": {}
        },
        "runtime": {
          "lib/netcoreapp3.0/CronScheduler.AspNetCore.dll": {}
        }
      }

All packages need to be updated to their 3.0 version. 
In StartupJobExtensions, the IWebHost reference gives an error. I commented it out in my local version, as it does not seem to be used anyway.

**Comment by vankampenp** [comment]
<ItemGroup>
    <PackageReference Include="Cronos" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.0.0" />
    
  </ItemGroup>

**Comment by kdcllc** [comment]
@tomkerkhove @vankampenp I released `2.0.0` version with breaking changes issue #27

**Comment by tomkerkhove** [comment]
Thank you for fixing this so quickly - It worked like a charm, thanks!

**Comment by hallidev** [comment]
Much appreciated!
