### ISSUE TITLE
Change cron schedule in appsettings at runtime

### ISSUE THREAD

**Issue by marlind89** [kdcllc/CronScheduler.AspNetCore#32]
Hello,

Is it possible to change the cron schedule of a job while the application is running?

I want to be able to change the cron schedule in appsettings without having to restart the application.

Thanks!

**Comment by kdcllc** [comment]
@langebangen at the present time the change to configuration only will apply to customer properties of the configuration and not the cron job. I am considering the issue #29 and also enabling to have OptionsMonitor interface for configurations that would allow for exactly the scenario you are asking for

**Comment by kdcllc** [comment]
@langebangen,

Branch https://github.com/kdcllc/CronScheduler.AspNetCore/blob/6398f0cd606df0b02626959629dc00bcc2610f3f/src/CronScheduler.Extensions/DependencyInjection/SchedulerBuilder.cs#L54

I  released a preview with functionality you request. Can you test it out?

Please add this to your nuget feed: https://f.feedz.io/kdcllc/cronscheduler-aspnetcore/nuget/index.json

In order for the options to update register the job:

```csharp
services.AddScheduler(builder =>
{
 builder.Services.AddJob<TestJob>();
}
```

Then inject `IOptionsMonitor<SchedulerOptions> options` -> `options.Get(nameof(TestJob).Name)

```csharp
        public TestJob(IOptionsMonitor<SchedulerOptions> optionsMonitor, ILogger<TestJob> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));

            var named = typeof(TestJob).Name;
            _options = optionsMonitor.Get(named);
            optionsMonitor.OnChange((o, n) =>
            {
                if (n == named)
                {
                    _options = o;
                }
            });
        }
```
Thanks, kdcllc

**Comment by marlind89** [comment]
Seems to be working for me 👍 Thank you for taking your time to implement this.
