### ISSUE TITLE
Named jobs: need an example

### ISSUE THREAD

**Issue by andToxa** [kdcllc/CronScheduler.AspNetCore#35]
Hello!
I need to schedule two jobs with same type but different options.
How can I do it? There is no example of named jobs.

**Comment by rdadkins** [comment]
I believe that the latest update doesn't support multiple jobs under the same type ([see here](https://github.com/kdcllc/CronScheduler.AspNetCore/blob/022ea1d0f38d1e469e34de6d53d530b7fc57e485/src/CronScheduler.Extensions/DependencyInjection/SchedulerBuilder.cs#L43-L45)).

**Comment by andToxa** [comment]
Is there plans to support multiple jobs with the same type in the future?

**Comment by kdcllc** [comment]
@rdadkins please see the latest version
