### ISSUE TITLE
[Proposal] Keyed jobs

### ISSUE THREAD

**Issue by rdadkins** [kdcllc/CronScheduler.AspNetCore#36]
The latest update provided support for jobs to defined at runtime but there's an issue with 'duplicate' jobs.

[Here](https://github.com/kdcllc/CronScheduler.AspNetCore/blob/022ea1d0f38d1e469e34de6d53d530b7fc57e485/src/CronScheduler.Extensions/DependencyInjection/SchedulerBuilder.cs#L43-L45) and [here](https://github.com/kdcllc/CronScheduler.AspNetCore/blob/022ea1d0f38d1e469e34de6d53d530b7fc57e485/src/CronScheduler.Extensions/Scheduler/SchedulerRegistration.cs#L48) we see that a job can only ever be registered once given its Type name. #35 is an example of this limitation - the same type of job cannot be registered twice with different `SchedulerOptions`.

I am personally running into this issue where I have my own job wrapper of type T and only the latest job will be registered.

I propose the following solution:
```
public interface IScheduledJob
{
  // All other fields and methods

  object Id { get; }
}
```

`Id` would represent a unique id in the eyes of SchedulerRegistration and it would check `IScheduledJob.Id` rather than `job.GetType().Name` during both `AddJob` and `RemoveJob`.

Or, change `ISchedulerRegistration` to:
```
public interface ISchedulerRegistration
{
  IReadOnlyDictionary<object, SchedulerTaskWrapper> Jobs { get; }

  bool AddOrUpdate(object id, IScheduledJob job);

  bool AddOrUpdate(object id, IScheduledJob job, SchedulerOptions options);

  bool Remove(object id);
}
```

**Comment by kdcllc** [comment]
@rdadkins this is a good proposal. The next version of the library will be a breaking change for all of the clients because `IScheduleJob` interface will drop all of its properties. I am considering adding `string Name` to this interface.

**Comment by rdadkins** [comment]
@kdcllc late update but this works perfectly for me. Thanks!
