### ISSUE TITLE
'ScheduledJob' is obsolete: Use SchedulerOptions with named job registration.

### ISSUE THREAD

**Issue by keyjote** [kdcllc/CronScheduler.AspNetCore#37]
Hi,
I just upgraded from version 2.0.1 to 2.1.0 and now I am getting the following warning
'ScheduledJob' is obsolete: 'Use SchedulerOptions with named job registration.'

As far as I can see in the example code for the readme, there were no strong changes from one version to the other.
My class is defined as:

    public class IceScheduledJob : ScheduledJob {
        protected IceScheduledJob(IceOptions options, IMyService myServices) : base(options) {

The code still runs but the warning is annoying. 
What am I doing wrong?

**Comment by keyjote** [comment]
Ok, nevermind, I think I found the issue.

And it is that SchedulerJob is set to obsolete and I should change to use ISchedulerJob instead (not SchedulerOptions).
That will push the options CronSchedule, RunImmediately and CronTimeZone into my IceScheduledJob.
In a way I can now set default values to them in case the options are empty. So I can see an improvement there.

I guess what threw me off was the documentation which does not reflect this changes.

Thanks anyway.

**Comment by tomkerkhove** [comment]
The doc fix is just a PR away ;)
