### ISSUE TITLE
How to inject IDistributedCache dependency?

### ISSUE THREAD

**Issue by thebentern** [kdcllc/CronScheduler.AspNetCore#40]
I'm having trouble getting an instance of IDistributed cache available to a job in my aspnet core application, and I think it's just a lack of understanding of the examples project code.
So the cache is registered in Startup with all of the other service registrations like so:

` services.AddStackExchangeRedisCache(options =>
            {
               ...
            });`

I have been unsuccessful at getting an instance of the IDistributedCache available to my job. The latest attempt was something along the lines of:
`using var scope = _serviceProvider.CreateScope();
 _distributedCache = scope.ServiceProvider.GetRequiredService<IDistributedCache>();`

If someone could shed some light on how to get things wired up correctly for this instance, that would be very helpful, because I'm stumped at the moment.

Thanks

**Comment by kdcllc** [comment]
@thebentern is it possible to have the sample project? Can you also provide with exception you are getting?
