### ISSUE TITLE
Can only schedule each job class once

### ISSUE THREAD

**Issue by tkunstek** [kdcllc/CronScheduler.AspNetCore#43]
In the file https://github.com/kdcllc/CronScheduler.AspNetCore/blob/master/src/CronScheduler.Extensions/Internal/SchedulerRegistration.cs line 48 it looks like a dictionary is being with the class name used as the key. If you try to add another job of the same class type but with different options or Name, it will replace your previously scheduled job. I propose changing the dictionary to be based on the schedule job Name property instead of GetType().Name.

**Comment by tomkerkhove** [comment]
I'm currently scheduling the same job class with different names and don't have any issues.

https://github.com/tomkerkhove/promitor/blob/74a8bee19b28b2798fa6ceafe5cc64372387a222/src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs#L72

**Comment by tkunstek** [comment]
I saw a unit test for this case, but it was testing during service registration and not using the AddOrUpdate method. When testing it using AddOrUpdate it would replace the job and I observed the name changing and the counts not increasing.

**Comment by bakker451** [comment]
I had the same problem when using the ISchedulerRegistration.AddOrUpdate() method to register jobs using the same class for each job. I can't use the SchedulerBuilder.AddJob() method in the startup code in my scenario. I really wanted a light weight scheduler and now have to ditch it and use Quartz instead. For context, job definitions are stored in a  database. Jobs are not executed by the scheduler they are executed by another service. When the scheduler runs a job all it does is send a message on a queue and then stops.

**Comment by kdcllc** [comment]
@tkunstek and @bakker451  I am sorry it took me a bit of time to complete the changes that both of you requested. Please refer to unit test for details of the usage https://github.com/kdcllc/CronScheduler.AspNetCore/blob/2e1124994c85bdd3c2a7f374141368781badf988/test/CronScheduler.UnitTest/SchedulerRegistrationTests.cs#L32.
Let me know if it works for you.
