### ISSUE TITLE
What is the CronSchedule notation?

### ISSUE THREAD

**Issue by juniair** [kdcllc/CronScheduler.AspNetCore#44]
I am a person who is currently developing in Korea using the CronSchedule system developed by you.

It is defined in `application.json` as follows so that it works at `3 AM` in Korean time (UTC +09:00) as follows.

```json
"TestJob": {
     "RunImmediately": true,
     "CronSchedule": "0 0 3 * * *",
}
```

After that, I checked the log at that time and it did not work.

If you check your code, the `SchedulerTaskWrapper` class sets the next operation time with `TimeZoneInfo.Local`. The parameter of `SchedulerTaskWrapper.ShouldRun` evaluates `DateTimeOffset.UtcNow` as a value.

Should CronSchedule be set based on `UTC +00:00`?

**Comment by kdcllc** [comment]
@juniair I am not sure if you figured it out or not. You should configure your time zone with:

```json
    "TestJob": {
      "CronSchedule": "*/5 * * * * *",
      "CronTimeZone": "",
      "RunImmediately": true
    }
```
To determine your time zone run the following code:
```csharp
namespace TimeZonesApp  
{  
    class Program  
    {  
        static void Main(string[] args)  
        {  
            foreach (TimeZoneInfo timeZone in TimeZoneInfo.GetSystemTimeZones()){  
                Console.WriteLine(timeZone.Id);  
            }  
        }  
    }  
}
```

reference code: https://github.com/kdcllc/CronScheduler.AspNetCore/blob/09450a4c8dc5f32d1a57aea5de2e10b41c61f780/src/CronScheduler.Extensions/Internal/SchedulerRegistration.cs#L102

I hope this helps.
