### ISSUE TITLE
Is there a way how to use IStartupJob in Asp.Net Core integration tests WebApplicationFactory<T>?

### ISSUE THREAD

**Issue by karelkral** [kdcllc/CronScheduler.AspNetCore#46]
Thanks for the excellent library.

Do you have any pattern of how to use IStartupJob and CronScheduler in WebApplicationFactory<TStartup>? I know that this is not an issue with CronScheduler, just asking for an opinion. 

Before CronScheduler, we had the async startup tasks implemented as simple IHostedService. Startup jobs were executed in IHostedService.ExecuteAsync(). This worked well with WebApplicationFactory<TStartup>.

We tried to convert our initialization to IStartupJob, which works well in Asp.Net application. 
But I cannot find a place where to call `await host.RunStartupJobsAync()` in WebApplicationFactory. 
Can you help?

**Comment by kdcllc** [comment]
@karelkral is it possible for you to provide with sample code?
