### ISSUE TITLE
Add `IServiceProvider` access when registering scheduled job 

### ISSUE THREAD

**Issue by stijnmoreels** [kdcllc/CronScheduler.AspNetCore#47]
**Describe the feature you would like to have:**
Currently, a scheduled job can be added without any `IServiceProvider` access. This can be rather tedious as when registering an `UnobservedTaskExceptionHandler`, one might want to use the registered `ILogger<>` instead.
In the sample app in this repo, we see the same problem recurring.

A possible way, is to add an overload that takes in `Action<SchedulerBuilder, IServiceProvider>` or something like that, so the configuration can access the `IServiceProvider` and the registered services.

[File to change](https://github.com/kdcllc/CronScheduler.AspNetCore/blob/3.0.1/src/CronScheduler.Extensions/DependencyInjection/SchedulerServiceCollectionExtensions.cs)

**Comment by kdcllc** [comment]
@stijnmoreels I am sorry for the delay in merging your changes. I completed your changes here https://github.com/kdcllc/CronScheduler.AspNetCore/pull/50

**Comment by stijnmoreels** [comment]
> @stijnmoreels I am sorry for the delay in merging your changes. I completed your changes here #50

Oh, that's great! 🥳 
Thx!
Hope it helps people when managing their scheduled jobs.
